stages:
  - build
  - push
  - deploy
 
build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  before_script:
    - echo "Setting up Docker environment"  
  script:
    - infra/00-build-image.sh

push:
  stage: push
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  before_script:
    - echo "Logging into Docker registry"  
  script:
    - infra/02-docker-login.sh
    - infra/03-upload-image.sh
  only:
    - main

deploy:
  stage: deploy
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  before_script:
    - echo "Docker set docker auth config"
    - infra/04-ssh-setup.sh
    - infra/05-deploy.sh

#   script:
#     - echo $API_PORT
#     - echo $IMAGE_NAME
#     - echo $TAG
#     - ssh -T -o StrictHostKeyChecking=no deployer@writeonce.de "
#         IMAGE_NAME=$IMAGE_NAME TAG=$TAG API_PORT=$API_PORT  \

#         docker run -d \
#           --name writeonce-manage-article-api \
#           --network writeonce-network \
#           -p \$API_PORT:\$API_PORT \
#           --restart always \
#           \$IMAGE_NAME:\$TAG
#       "
#     - ssh-agent -k
  # only:
  #   - main