FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig


RUN dpkg --add-architecture arm64 && \
  apt-get update && \
  apt-get install -y \
  curl \
  build-essential \
  pkg-config \
  libssl-dev \
  libpq-dev:arm64 \
  && rm -rf /var/lib/apt/lists/*

